### PR TITLE
Fixes Storage Error if any storage is disabled in the PVE

### LINKED ISSUE #419: Storage Error if any storage is disabled in the PVE
**Describe the bug**
When trying to create anything in the PVE, and the PVE has disabled storage, an exception is thrown which  is saying:

> Oops, we're sorry but something went wrong Expected([200]) <=> Actual(500 InternalServerError) excon.error.response :body => "{\"message\":\"storage 'local-zfs' is disabled\\n\",\"data\":null}" :cookies => [ ] :headers => { "Cache-Control" => "max-age=0" "Connection" => "close" "Content-Length" => "59" "Content-Type" => "application/json;charset=UTF-8" "Date" => "Fri, 18 Jul 2025 10:55:16 GMT" "Expires" => "Fri, 18 Jul 2025 10:55:16 GMT" "Pragma" => "no-cache" "Server" => "pve-api-daemon/3.0" } :host => "10.140.36.1" :local_address => "10.140.33.134" :local_port => 56782 :method => "GET" :omit_default_port => true :path => "/api2/json//nodes/pve01/storage/local-zfs/content" :port => 8006 :query => "" :reason_phrase => "storage 'local-zfs' is disabled" :remote_ip => "10.140.36.1" :scheme => "https" :status => 500 :status_line => "HTTP/1.1 500 storage 'local-zfs' is disabled\r\n" 

**Report**

> 55936d90 | excon.error.response
>  55936d90 |   :body              => "{\"message\":\"storage 'local-zfs' is disabled\\n\",\"data\":null}"
>  55936d90 |   :cookies           => [
>  55936d90 |   ]
>  55936d90 |   :headers           => {
>  55936d90 |     "Cache-Control"  => "max-age=0"
>  55936d90 |     "Connection"     => "close"
>  55936d90 |     "Content-Length" => "59"
>  55936d90 |     "Content-Type"   => "application/json;charset=UTF-8"
>  55936d90 |     "Date"           => "Fri, 18 Jul 2025 10:55:16 GMT"
>  55936d90 |     "Expires"        => "Fri, 18 Jul 2025 10:55:16 GMT"
>  55936d90 |     "Pragma"         => "no-cache"
>  55936d90 |     "Server"         => "pve-api-daemon/3.0"
>  55936d90 |   }
>  55936d90 |   :host              => "1.2.3.4"
>  55936d90 |   :local_address     => "1.2.3.4"
>  55936d90 |   :local_port        => 56782
>  55936d90 |   :method            => "GET"
>  55936d90 |   :omit_default_port => true
>  55936d90 |   :path              => "/api2/json//nodes/pve01/storage/local-zfs/content"
>  55936d90 |   :port              => 8006
>  55936d90 |   :query             => ""
>  55936d90 |   :reason_phrase     => "storage 'local-zfs' is disabled"
>  55936d90 |   :remote_ip         => "1.2.3.4"
>  55936d90 |   :scheme            => "https"
>  55936d90 |   :status            => 500
>  55936d90 |   :status_line       => "HTTP/1.1 500 storage 'local-zfs' is disabled\r\n"
>  55936d90 | 

**To Reproduce**
1. Go to Infrastructure -> Compute Resources -> PVE (or how it is named)
2. Click on "Create Image"

**Expected behavior**
Working with the PVE Compute Resource.

**System Information**

hammer status:

> Version:          3.15.0
> API-Version:      v2
> Datenbank:        
>     Status:        ok
>     Serverantwort: Dauer: 1ms
> Plugins:          
>  1) Name:    foreman-tasks
>     Version: 11.0.0
>  2) Name:    foreman_fog_proxmox
>     Version: 0.18.1
>  3) Name:    foreman_remote_execution
>     Version: 16.0.3
>  4) Name:    katello
>     Version: 4.17.0
> Smart Proxys:     
>  1) Name:       myforemanhost
>     Version:    3.15.0
>     Status:     ok
>     Funktionen: 
>      1) Name:    pulpcore
>         Version: 3.4.0
>      2) Name:    logs
>         Version: 3.15.0

What is to do, that Foreman ignores disabled storage?

Thanks in advance!

### PR DESCRIPTION
**Pull request by Manisha15**
Fixes #419

### CODE REVIEW

File: app/models/foreman_fog_proxmox/proxmox_images.rb [hunk 1]
```diff
@@ -48,11 +48,22 @@ def templates
...
+          unless storage.enabled.to_i == 1
+            logger.warn("Skipping disabled storage #{storage.identity} on #{node.node}")
+            next
+          end
 
-          # fetches volumes of KVM containers for images
+          # Fetch QEMU and LXC template images
+          volumes += storage.volumes.list_by_content_type('images')
           volumes += storage.volumes.list_by_content_type('rootdir')
+        rescue Excon::Error::InternalServerError => e
```
Comment (sbernhard) [inline app/models/foreman_fog_proxmox/proxmox_images.rb]: why is this necessary if there is also the block in https://github.com/theforeman/foreman_fog_proxmox/pull/433/files#diff-27f981f2a27945b7d516f049a4b2057837ba64ee9c6025792fab958e2670253aR52?

File: app/models/foreman_fog_proxmox/proxmox_images.rb [hunk 2]
```diff
@@ -48,11 +48,22 @@ def templates
...
+          raise unless e.message.include?("storage '#{storage.identity}' is disabled")
+          logger.warn("Storage #{storage.identity} on #{node.node} is disabled (API error), skipping")
+          next
+        rescue StandardError => e
+          logger.error("Failed to fetch volumes for storage #{storage.identity} on #{node.node}: #{e.message}")
+          next
```
Comment (sbernhard) [inline app/models/foreman_fog_proxmox/proxmox_images.rb]: What is the purpose of this 'next'?

File: app/models/foreman_fog_proxmox/proxmox_images.rb (hunk 1 above)
Comment (Manisha15) [reply app/models/foreman_fog_proxmox/proxmox_images.rb]: to catch error if storage fetch fails due to permission issue or if the compute resource is not able to fetch storages from other nodes.

**Review by sbernhard — APPROVED** [review]
