### PR TITLE
Fixes deletion of foreman host if associated vm doesn't exist in proxmox server

### LINKED ISSUE #269: Host cannot be deleted in Foreman if associated VM in Proxmox no longer exists
If the vm associated with Foreman host does not exist in proxmox server then deleting the foreman host throws error.

Steps to Reproduce:
1. Delete in foreman a host where the associated VM in Proxmox no longer exists.

Actual results:
Foreman throws an error and does not delete the host.

Expected results:
Host in Foreman is deleted.

Additional info:
Host can only be deleted after disassociating it or if `Destroy associated VM on host delete` in settings is set to `No`.

### PR DESCRIPTION
**Pull request by Manisha15**
Fixes #269

### CODE REVIEW

File: app/models/foreman_fog_proxmox/proxmox_vm_commands.rb [hunk 1]
```diff
@@ -55,7 +55,9 @@ def create_vm(args = {})
 
     def destroy_vm(uuid)
       vm = find_vm_by_uuid(uuid)
-      unless vm.nil?
+      if vm.nil?
```
Comment (sbernhard) [inline app/models/foreman_fog_proxmox/proxmox_vm_commands.rb:58]: More ruby like:
```
return true if vm.nil?

vm.stop if vm.ready?
vm.destroy
```

maybe think also about using a try/catch block. Verify how this is done for other compute resources, too.

Comment (Manisha15) [reply app/models/foreman_fog_proxmox/proxmox_vm_commands.rb:58]: For other compute resources if they cannot find the vm then they throw `ActiveRecord::RecordNotFound` error which is caught by rescue condition. But in proxmox if the vm is not found it returns `nil` which cannot be caught by try/catch method.

Comment (sbernhard) [reply app/models/foreman_fog_proxmox/proxmox_vm_commands.rb]: thanks.

**Review by sbernhard — APPROVED** [review]
