### PR TITLE
Fixes mac address change on editing host

### LINKED ISSUE #213: Mac Address Change when Edit Host
**Describe the bug**
If values such as CPU, memory or similar are changed in a VM via the WebUI of foreman (Edit VM), a new NIC Mac address is generated each time.
This Mac address is not known to foreman and its DHCP, so the VM in question gets a new IP from the DHCP and the name resolution no longer works.

**Foreman Version**
Foreman 2.5.4

**Proxmox Version 7.0-8**

**To Reproduce**
1. Go to Foreman  -> Hosts -> All Hosts
2. Click on a Host
3. Click on Edit
4. Click on Virtual Machine Tab
5. Check the CPU Box for example 
6. Edit CPU Core count value
3. Scroll down to Submit
4. Click on Submit

**Expected behavior**
The MAC Address should not be changed

**Screenshots**
pve2 - Proxmox Virtual Environment 2021-10-26 12-37-30

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome 
 - Version 95.0.4638.54

### PR DESCRIPTION
**Pull request by Manisha15**
Fixes #213

### CODE REVIEW

File: app/helpers/proxmox_vm_config_helper.rb [hunk 1]
```diff
@@ -27,11 +27,11 @@
...
   def object_to_config_hash(vm, type)
     vm_h = ActiveSupport::HashWithIndifferentAccess.new
-    main_a = ['vmid']
-    main = vm.attributes.select { |key, _value| main_a.include? key }
+    main_a = ['vmid', 'type']
+    main = vm.attributes.select { |key, _value| main_a.include? key.to_s }
     main_a += ['templated']
     config = vm.config.attributes.reject do |key, _value|
-      main_a.include?(key) || Fog::Proxmox::DiskHelper.disk?(key) || Fog::Proxmox::NicHelper.nic?(key)
+      main_a.include?(key.to_s) || Fog::Proxmox::DiskHelper.disk?(key) || Fog::Proxmox::NicHelper.nic?(key)
```
Comment (m-bucher) [inline app/helpers/proxmox_vm_config_helper.rb:34]: Should we also use `key.to_s` for `DiskHelper.disk?` and `NicHelper.nic?`, too`

File: app/helpers/proxmox_vm_interfaces_helper.rb [hunk 2]
```diff
@@ -56,7 +56,8 @@ def interface_compute_attributes_typed_keys(type)
   end
 
   def interface_common_typed_keys(type)
-    [{ origin: 'id', dest: 'id' }, { origin: 'mac', dest: type == 'qemu' ? 'macaddr' : 'hwaddr' }]
+    mac = type == 'qemu' ? 'macaddr' : 'hwaddr'
+    [{ origin: 'id', dest: 'id' }, { origin: mac, dest: mac }]
```
Comment (m-bucher) [inline app/helpers/proxmox_vm_interfaces_helper.rb:60]: If `origin` and `dest` are the same in both cases, is this necessary at all?

File: app/helpers/proxmox_vm_config_helper.rb (hunk 1 above)
Comment (Manisha15) [reply app/helpers/proxmox_vm_config_helper.rb:34]: No, to match with the keys in a list we need to convert them to string but for disl and nic, it can take key as symbol as well.

File: app/helpers/proxmox_vm_interfaces_helper.rb (hunk 2 above)
Comment (Manisha15) [reply app/helpers/proxmox_vm_interfaces_helper.rb]: changed it to only add the keys as a list.

**Review by sbernhard — APPROVED** [review]
